In [2]:
import numpy as np

## Aşağıdaki arr1 arrayinin orta satırını ve son sütunu seçin:

In [90]:
arr1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [91]:
arr1[1, :-1]

array([4, 5])

## Arrayin son satırını ters çevirerek seçin:

In [92]:
arr1[-1, ::-1]

array([9, 8, 7])

## Arrayin köşegen elemanlarını seçin:
**Derste görmediniz. Araştırma gerekiyor.**

In [93]:
arr1.diagonal()

array([1, 5, 9])

## Arrayin alt üçgenini seçin:
**Derste görmediniz. Araştırma gerekiyor.**

In [96]:
arr1[np.tril_indices(3)]

array([1, 4, 5, 7, 8, 9])

## Arrayin üst üçgenini seçin:
**Derste görmediniz. Araştırma gerekiyor.**

In [95]:
arr1[np.triu_indices(3)]

array([1, 2, 3, 5, 6, 9])

## Arrayin elemanlarını rastgele karıştırarak seçin:
**Derste görmediniz. Araştırma gerekiyor.**

In [97]:
np.random.shuffle(arr1)
arr1

array([[4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]])

## Aşağıdaki arr2 arrayinin satırlarını toplayarak seçin:

In [17]:
arr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [29]:
np.sum(arr2, axis=1)

array([10, 26, 42, 58])

## Arrayin 3. satırındaki en büyük ve en küçük elemanları seçin:

In [33]:
max_val = np.max(arr2[2])
min_val = np.min(arr2[2])
print(f"max_val: {max_val}, min_val: {min_val}")

max_val: 12, min_val: 9


## Aşağıdaki arr3 arrayinin 5'ten küçük elemanlarını olduğu gibi, diğer elemanları 10 ile çarparak getirin:

In [61]:
arr3 = np.arange(10)
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
np.where(arr3 < 5, arr3, 10*arr3)

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

# Aşağıdaki arr4 array'inin 1. ve 3. sütunlarındaki 5'ten büyük elemanlarını olduğu gibi, bu sütunların diğer elemanlarını 0 olarak getirin:

In [64]:
arr4 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
arr4

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [66]:
arr4[:, [0, 2]]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15]])

In [67]:
cond = arr4[:, [0, 2]] > 5
cond

array([[False, False],
       [False,  True],
       [ True,  True],
       [ True,  True]])

In [69]:
np.where(arr4 > 5, arr4, 0)[:, [0, 2]]
# np.where(arr4 > 5, arr4, False)[:, [0, 2]]

array([[ 0,  0],
       [ 0,  7],
       [ 9, 11],
       [13, 15]])

# Arrayin 1. ve 4. sütunlarındaki 10'dan büyük ve eşit elemanları "büyük", bu sütunların diğer elemanlarını "küçük" olarak değiştirin:

In [72]:
cond = arr4[:, [0, 3]] >= 10
cond

array([[False, False],
       [False, False],
       [False,  True],
       [ True,  True]])

In [73]:
# nested where

np.where(arr4 >= 10, "büyük", np.where(arr4 < 10, "küçük", arr4))[:, [0, 3]]

array([['küçük', 'küçük'],
       ['küçük', 'küçük'],
       ['küçük', 'büyük'],
       ['büyük', 'büyük']], dtype='<U11')

## Aşağıdaki arr2D dizisini, 2. satırını arr1D dizisi ile toplayacak şekilde update edin.:

In [75]:
arr2D = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr1D = np.array([10, 20, 30])

display(arr2D)
display(arr1D)

array([[1, 2, 3],
       [4, 5, 6]])

array([10, 20, 30])

In [89]:

arr2D[1, :] = arr2D[1, :] + arr1D
arr2D

array([[ 1,  2,  3],
       [24, 45, 66]])