<a href="https://clarusway.com/contact-us/"><img align="center" src="https://i.ibb.co/B43qn24/officially-licensed-logo.png" alt="Open in Clarusway LMS" width="110" height="200" title="This notebook is licensed by Clarusway IT training school. Please contact the authorized persons about the conditions under which you can use or share."></a>

<hr>

<a href="https://lms.clarusway.com/mod/lesson/view.php?id=2463&pageid=4531&startlastseen=no"><img align="center" src="https://i.ibb.co/6Z5pQxD/lmss.png" alt="Open in Clarusway LMS" width="70" height="200" title="Open Clarusway Learning Management Sytem"></a>

<a href="https://github.com/clarusway/DS-DE-0322-Students/blob/main/3-%20Classes%26Labs/2-DAwPY/DAwPy_S01_(Numpy_Arrays).ipynb"><img align="left" src="https://i.ibb.co/n3HWyQX/github-logo.png" alt="Open in Clarusway GitHub" width="90" height="150" title="Open and Execute in Clarusway GitHub Repository"></a>

<a href="https://nbviewer.org/github/4dsolutions/clarusway_data_analysis/blob/main/DAwPy_S1_%28Numpy_Arrays%29/DAwPy_S1_%28Numpy_Arrays%29.ipynb"><img align="right" src="https://i.ibb.co/48wtV8c/nbviewer-badge.png" alt="Open in nbviewer" width="100" height="100" title="Open and Execute in nbviewer"></a><br/>

<hr>

<p style="text-align: center;"><img src="https://i.ibb.co/Rpz9L36/clarusway-logo-black.png" width="500" height="200" class="img-fluid" alt="CLRSWY_LOGO"></p>

<p style="text-align: center;"><img src="https://i.ibb.co/XS0bxSH/best-bootcamps.png" width="300" height="200" class="img-fluid" alt="CLRSWY_LOGO"></p>

<p style="background-color:#E51A59; font-family:newtimeroman; color:#FDFEFE; font-size:130%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

<p style="text-align: center;"><img src="https://i.ibb.co/99DQ3TY/DS-Courses.png" class="img-fluid" 
alt="CLRSWY_Courses"></p>

# <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">Tasks for Session-1</p>

In [1]:
import numpy as np

## Task 1 : Task: Random Matrix Generation and Operations:

### 1a. Generate a 4x4 matrix filled with random values.

In [2]:
matrix = np.random.rand(4, 4)
matrix

array([[0.5834853 , 0.76604735, 0.32304425, 0.75985418],
       [0.53596343, 0.55703288, 0.38746523, 0.81513161],
       [0.05702913, 0.77887421, 0.54776028, 0.77977014],
       [0.17991057, 0.49002502, 0.96441255, 0.00214067]])

### 1b. Calculate the row sums of the matrix.

In [3]:
np.sum(matrix, axis=1)

array([2.43243108, 2.29559316, 2.16343376, 1.63648881])

### 1c. Calculate the column means of the matrix.

In [4]:
np.mean(matrix, axis=0)

array([0.33909711, 0.64799486, 0.55567058, 0.58922415])

### 1d. Find the sum of the diagonal elements of the matrix.

In [5]:
np.trace(matrix)

1.6904191396092152

## Task 2: Array Sorting and Indexing:

### 2a. Create an array of random numbers from 1 to 20.

In [6]:
array = np.random.randint(1, 21, size=10)
array

array([20, 13, 14,  1, 10,  3, 16, 16, 13, 15])

### 2b. Sort the array in descending order.

In [7]:
np.sort(array)[::-1]

array([20, 16, 16, 15, 14, 13, 13, 10,  3,  1])

### 2c. Find the minimum and maximum elements of the array.

In [8]:
min_element = np.min(array)
max_element = np.max(array)

print("Minimum element:", min_element)
print("Maximum element:", max_element)

Minimum element: 1
Maximum element: 20


### 2d. Select the first half of the array (the first 10 elements) and reverse them.

In [9]:
half_array = array[:len(array)//2]

reversed_half_array = half_array[::-1]

print(array)
print(reversed_half_array)

[20 13 14  1 10  3 16 16 13 15]
[10  1 14 13 20]


## Task 3: Convert the Arrays:

### 3a. Create an array with elements [-1, 0, 1, 2, 3].

In [10]:
array = np.array([-1, 0, 1, 2, 3])
array

array([-1,  0,  1,  2,  3])

In [11]:
array.shape

(5,)

### 3b. Convert the array into a matrix and square each element.

In [12]:
matrix = np.reshape(array, (1, -1))
# matrix = np.matrix(array)  # alternative solution
print(matrix)

squared_matrix = np.square(matrix)
print(squared_matrix)

[[-1  0  1  2  3]]
[[1 0 1 4 9]]


### 3c. Convert the matrix back to a one-dimensional array.

In [13]:
np.reshape(array, (5,))

array([-1,  0,  1,  2,  3])

### 3d. Convert each element of the array to its absolute value

In [14]:
abs_array = np.abs(array)
abs_array

array([1, 0, 1, 2, 3])

<hr>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:150%; text-align:center; border-radius:10px 10px;">The End of Task</p>


<p style="text-align: center;"><img src="https://i.ibb.co/99DQ3TY/DS-Courses.png" class="img-fluid" 
alt="CLRSWY"></p>


<br><br><br>

<p style="text-align: center;"><img src="https://i.ibb.co/Rpz9L36/clarusway-logo-black.png" width="450" height="200" class="img-fluid" alt="CLRSWY_LOGO"></p>

<p style="background-color:#E51A59; font-family:newtimeroman; color:#FDFEFE; font-size:130%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

<a href="https://clarusway.com/contact-us/"><img align="center" src="https://i.ibb.co/B43qn24/officially-licensed-logo.png" alt="Open in Clarusway LMS" width="110" height="200" title="This notebook is licensed by Clarusway IT training school. Please contact the authorized persons about the conditions under which you can use or share."></a>